version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_shop
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - postgres_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
